### PR TITLE
Fix rubocop issues

### PR DESCRIPTION
**Pull request by TraGicCode**

### CODE REVIEW

**Comment by bastelfreak** [comment]
why is there no travis running...

**Comment by bastelfreak** [comment]
yey

**Comment by TraGicCode** [comment]
@bastelfreak I can check this when I get home.  Briefly looking at the error it sounds like this might be a puppet-rspec error where running Windows specific things on a non windows machine doesn't work right

**Comment by TraGicCode** [comment]
@bastelfreak Solved the issue.  Needed to set a fact to windows to allow for puppet-rspec to pretend to be a specific O/S.

**Comment by TraGicCode** [comment]
Crap worked on my MAC and windows but not travis ..

**Comment by TraGicCode** [comment]
@bastelfreak It looks like this works fine running
```
bundle exec rake spec_prep
bundle exec rake spec_standalone
```
But when running the test in parallel, which travis ci does, with `bundle exec rake test` causes some issues. Any idea on how to solve this issues?

**Comment by bastelfreak** [comment]
I've no idea why this is happening :(

**Comment by TraGicCode** [comment]
I'm Going to open a ticket on rspec-puppet and refence this.

**Comment by TraGicCode** [comment]
@bastelfreak This guys branch will resolve this issue once it gets merged into spec-puppet

rodjek/rspec-puppet#608

**Comment by TraGicCode** [comment]
@bastelfreak I've added an appveyor.yml.  Here are my notes:

1.) I see i can login to appveyor under your account ( or team not sure what it's called ) but i cannot do anything but view projects.  I think you need to apply permissions on your end.

2.) My appveyor doesn't do a matrix.  Since we are using the free version jobs don't run in parallel so it is a waste of time.  Should part of this run under travis?  Also how do we need to handle releasing etc?

**Comment by TraGicCode** [comment]
@bastelfreak I aborted the whole appveyor approach for now.  In order to solve the issues with not running on travis-ci i had to remove the catalog compilation test ( which isn't ideal ) but it allows the rspec-tests to run on both windows and non-windows now.  I also went ahead and fixed the rubocop violations.  I Would like to get this merged in so i can do a first release on the forge.

**Pull request merged**
